services:
  # Service 1: The Django Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: peekachiu/strada-backend:latest
    container_name: strada_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - DB_HOST=
    command: python manage.py runserver 0.0.0.0:8000 # Use dev server for now for auto-reload

  # Service 2: The Nginx Web Server
  nginx:
    build:
      context: ./frontend
      dockerfile: nginx/Dockerfile
    image: peekachiu/strada-frontend:latest
    container_name: strada_frontend
    ports:
      - "80:80" # Maps localhost:80 to Nginx
    environment:
      - API_HOST=backend:8000
    volumes:
      - ./frontend/public:/usr/share/nginx/html # Mount your frontend folder
      - ./backend/static:/app/static # Mount static files (for admin)
    depends_on:
      - backend
